---
- apt: name=lxc state=present
  sudo: yes

- lineinfile: dest=/etc/dhcp/dhclient.conf line="prepend domain-name-servers {{ lxc_bridge_addr }};" insertafter="^#prepend domain-name-servers 127.0.0.1;"
  notify: restart lxc_bridge_out_if
  sudo: yes
