---
- lineinfile: dest=/etc/sysconfig/iptables
              line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT"
              insertbefore="-A INPUT -j REJECT --reject-with icmp-host-prohibited"
  sudo: yes
  notify: restart iptables

- lineinfile: dest=/etc/sysconfig/iptables
              line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT"
              insertbefore="-A INPUT -j REJECT --reject-with icmp-host-prohibited"
  sudo: yes
  notify: restart iptables
