---
- include_vars: "{{ ansible_os_family }}.yml"

- apt: name=ntp state=present
  when: ansible_os_family == "Debian"

- yum: name=ntp state=present
  when: ansible_os_family == "RedHat"

- template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart {{ ntp_service_name }}

- service: name={{ ntp_service_name }} state=started enabled=yes
