---
- name: restart lxc-net
  sudo: yes
  shell: service lxc-net stop && serivice lxc-net start

- name: restart lxc_bridge_out_if
  sudo: yes
  shell: ifdown {{ lxc_bridge_out_if }} && ifup {{ lxc_bridge_out_if }}
