---
- apt_key: url={{ nginx_signing_key_url }} state=present
  sudo: yes

- apt_repository: repo='deb {{ nginx_stable_repo_base_url }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx' state={{ nginx_stable_state }}
  sudo: yes
  register: nginx_stable_repo

- apt_repository: repo='deb-src {{ nginx_stable_repo_base_url }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx' state={{ nginx_stable_state }}
  sudo: yes

- apt_repository: repo='deb {{ nginx_mainline_repo_base_url }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx' state={{ nginx_mainline_state }}
  sudo: yes
  register: nginx_mainline_repo

- apt_repository: repo='deb-src {{ nginx_mainline_repo_base_url }}/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} nginx' state={{ nginx_mainline_state }}
  sudo: yes

- apt: update_cache=yes cache_valid_time=0
  sudo: yes
  when: nginx_stable_repo|changed or nginx_mainline_repo|changed

# NOTE: Uninstall and then reinstall nginx when nginx_branch is changed between stable and mainline.
- apt: name=nginx state=absent
  sudo: yes
  when: nginx_stable_repo|changed or nginx_mainline_repo|changed

- apt: name=nginx state=present
  sudo: yes
